### ISSUE TITLE
 s.type is not a constructor

### ISSUE THREAD

**Issue by MaximusMcfly** [l0c4lh057/AccountSwitcher#15] opened 2020-02-28 09:50 UTC
AccountSwitcher.plugin.js
Could not be constructed.
s.type is not a constructor

**Comment by MaximusMcfly** [comment] 2020-02-28 09:52
if screenshot is needed i can send

**Comment by l0c4lh057** [comment] 2020-02-28 17:06
duplicate of #1

**Closed by l0c4lh057** 2020-02-28 17:06 UTC
Labels: bug, cant reproduce, duplicate
